### PR TITLE
add compability for spatie/eloquent-sortable 4 and add nova dependency

### LINKED ISSUE #30: Allow spatie/sortable Version 4
The current composer constraint only allows version 3.

### PR DESCRIPTION
**Pull request by mstaack**
fixes #30

### CODE REVIEW

**Comment by mstaack** [comment]
@michielkempen can you please merge this soon? let me know if you need any help.

**Comment by mstaack** [comment]
@michielkempen are you still around? :)

**Comment by michielkempen** [comment]
Hey @mstaack, thanks for your contribution. I just tagged a new version (2.1.0) that incorporates your changes.

**Comment by mstaack** [comment]
thank you!

**Pull request merged**
